# Machine Learning Zoomcamp

## 1.7 Introduction to NumPy

Plan:
- Creating arrays
- Multi-demensional arrays
- Randomly generated arrays
- Element-wise operations
    - Comparison operations\
    - Logical operations
- Summarizing operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

### Creating arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [10]:
a[2] = 10

In [12]:
a[2]

np.int64(10)

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [15]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-demensional arrays

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [20]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
n[0,1] = 20

In [23]:
n[0,1] 

np.int64(20)

In [25]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
n[0]

array([ 1, 20,  3])

In [26]:
n[2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [29]:
n[:,1]

array([20,  5,  1])

In [30]:
n[:,2] = [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### Randomly generated arrays

In [39]:
np.random.seed(2)
np.random.rand(5,2) * 100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [38]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

### Element-wise operations

you can do this with arrays, but not lists

In [40]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [41]:
a+1

array([1, 2, 3, 4, 5])

In [43]:
b = (10 + (a*2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [45]:
a/b+10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

### Comparison operations

In [46]:
a >= 2

array([False, False,  True,  True,  True])

In [47]:
a > b

array([False, False,  True,  True,  True])

In [48]:
a[a>b]

array([2, 3, 4])

### Summarizing operations

In [49]:
a.min()

np.int64(0)

In [50]:
a.max()

np.int64(4)

In [51]:
a.sum()

np.int64(10)

In [53]:
a.std()

np.float64(1.4142135623730951)