# 1.8 Linear Algebra Refresher

Plan:
- Vector operations
- Multiplication
    - Vector-vector multiplication
    - Matrix-vector multiplication
    - matrix-matrix multiplication
- Identity matrix
- Inverse

In [2]:
import numpy as np

### Vector operations

In [3]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])
u+v

array([3, 4, 5, 8])

### Multiplication

In [18]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [19]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [20]:
u.dot(v)

np.int64(14)

In [21]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [22]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)


    return result

In [23]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [24]:
U.dot(v)

array([14,  5,  5])

In [25]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [29]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:, i] = Uvi
    return result

In [30]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [31]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [32]:
# identity matrix is like multiplying a matrix by 1, it is a square matrix with 1s on the diag and 0s elsewhere. 

In [38]:
I = np.eye(3)

In [ ]:
V.dot(I_